modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId="create"
    mandatory=true
    versionRange="[6.0.6,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="createdeco"
    mandatory=true
    versionRange="[2.0.0,2.9.9)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="create_freight.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"